name: pdf-bea
base: core18
version: '0.1'
summary: Graphical User Interface for pdf toolkit
description: |
  Bea is not an Ubuntu power user. She needs an utility to manipulate
  PDF files but she is not familiar with the terminal. This snap
  provides a graphical user interface for pdf utility.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
parts:
  pdf-bea:
    plugin: go
    go-importpath: github.com/mberlanda/pdf-bea
    source: https://github.com/mberlanda/pdf-bea
    source-type: git
    build-packages:
    - gcc
    - libgl1-mesa-dev
    - xorg-dev

apps:
  pdf-bea:
    command: bin/pdf-bea
